# Config PVC from HELM example for NFS
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sharedir
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi